### ISSUE TITLE
Should the helm chart have a PSP?

### ISSUE THREAD

**Issue by smlx** [opensearch-project/opensearch-devops#19]
PodSecurityPolicies are [deprecated](https://kubernetes.io/blog/2021/04/06/podsecuritypolicy-deprecation-past-present-and-future/) and will be removed from Kubernetes in the next year or so. Does it make sense for a new chart to support a deprecated API?

**Comment by DandyDeveloper** [comment]
@smlx Yes. They should, because many people will not be on the latest k8s version and could still be running 1.18 or even 1.16. 

Since we offer to enable/disable. I think the current implementation is fine, BUT we could have something like;

```
{{- if semverCompare "<1.9-0" .Capabilities.KubeVersion.GitVersion -}}
```

As an additional check to verify the Kubernetes version and to dictate whether the PSP should be written (enabled or not).

**Comment by peterzhuamazon** [comment]
@smlx is there any more questions you want to resolve related to PSP?
Shall we close this issue if not?
Thanks.

**Comment by smlx** [comment]
Yes my question is answered, thanks. Closing.
