### ISSUE TITLE
How to user document-level security to manage logging in opensearch dashboard?

### ISSUE THREAD

**Issue by lsy1990** [opensearch-project/opensearch-devops#75]
### Is your feature request related to a problem? Please describe

I want to use opensearch to store log that from kubernetes.To avoid  the count of the index is two many ,I use only one index named app-log,and this contain one field kubernetes.namespace,I want someone only query in one namespace,so create role and use bool filter,But what should i do in opensearch  to make user  only search the specifial namespace by index-pattern> 

### Describe the solution you'd like

I want to use opensearch to store log that from kubernetes.To avoid  the count of the index is two many ,I use only one index named app-log,and this contain one field kubernetes.namespace,I want someone only query in one namespace,so create role and use bool filter,But what should i do in opensearch  to make user  only search the specifial namespace by index-pattern>

**Comment by peterzhuamazon** [comment]
Not sure this is related to automation. Is this something specific to OpenSearch itself? Then it should go to OpenSearch core repo.

**Comment by gaiksaya** [comment]
Hi @lsy1990 Did you check https://opensearch.org/docs/latest/security/access-control/document-level-security/

Not sure what version of opensearch you are running since this issue seems pretty old. 
Closing this issue as stale. Please feel free to re-open the issue or try forum https://forum.opensearch.org/ for more questions.
Thanks!
